name: Build and Publish PDFs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-lang-chinese fonts-noto-cjk fonts-dejavu
        sudo apt-get install -y pandoc

    - name: Build PDFs
      run: |
        pandoc CV-EN.md -o CV-EN.pdf --pdf-engine=xelatex -V CJKmainfont="Noto Sans CJK SC" -V mainfont="DejaVu Serif" -V geometry:margin=1in -V fontsize=12pt
        pandoc CV-ZH.md -o CV-ZH.pdf --pdf-engine=xelatex -V CJKmainfont="Noto Sans CJK SC" -V mainfont="DejaVu Serif" -V geometry:margin=1in -V fontsize=12pt
        pandoc Resume-EN.md -o Resume-EN.pdf --pdf-engine=xelatex -V CJKmainfont="Noto Sans CJK SC" -V mainfont="DejaVu Serif" -V geometry:margin=1in -V fontsize=12pt
        pandoc Resume-ZH.md -o Resume-ZH.pdf --pdf-engine=xelatex -V CJKmainfont="Noto Sans CJK SC" -V mainfont="DejaVu Serif" -V geometry:margin=1in -V fontsize=12pt

    - name: Upload PDFs to GitHub Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PDFs
        path: |
          CV-EN.pdf
          CV-ZH.pdf
          Resume-EN.pdf
          Resume-ZH.pdf

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}-${{ github.run_id }}  # 生成版本号
        release_name: Release v${{ github.run_number }}-${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
